### ISSUE TITLE
Aide Workplace pour Sass

### ISSUE THREAD

**Issue by tobudim** [Artur01300/ohmayfood#1]
### Le problème :
Lorsque tu déplaces du code d'un fichier à un autre, ton site ne ressemble pas à ce que tu veux.

### Pourquoi ?
Comme spécifié sur Workplace : _css specificity_. Je te recommande de passer 30-40 minutes à lire sur le sujet.

### Comment faire ?
Déjà, tu fais référence à des fichiers qui n'existent pas ici :
https://github.com/Artur01300/ohmayfood/blob/4b9285c4526bff9715cd6e0424356e1b167c37e5/sass/main.scss#L5-6

C'est censé ne pas fonctionner. En tous cas quand je fais : 
```bash
sass sass/main.scss css/styles.css
```

J'ai des erreurs comme celle-ci :
```bash
Error: Can't find stylesheet to import.
  ╷
3 │ @import "la-palette-du-gout";
  │         ^^^^^^^^^^^^^^^^^^^^
  ╵
```

Déjà, donc, **dans main.scss n'importe que des fichiers qui existent.**

Ensuite, pourquoi mettre le contenu de _la-note-enchantee.scss_ et _le-chic-a-la-francaise.scss_ dans _main.scss_ ? **Il est mieux de diviser, ranger, séparer ton code en plusieurs modules.**

Quand tu importe un fichier comme ceci :
```scss
@import "media";
body {
  margin: auto;
}
``` 

Le contenu de _media.scss_ sera interprété avant le contenu suivant dans _main.scss_. 

### Exemples
Ici, le fond de ton site sera vert :
```scss
// media.scss
body { background-color: red }
```

```scss
// main.scss
@import "media";
body { background-color: green }
```

Mais ici, le fond de ton site sera rouge :
```scss
// main.scss
body { background-color: green }
body { background-color: red }
```

C'est le problème que tu avais.
Ce que tu disais, c'est de déplacer le contenu de _la-note-enchantee.scss_ et _le-chic-a-la-francaise.scss_ dans _main.scss_.
Et bien, refais la même chose, sauf que cette fois-ci : mets le contenu de _la-note-enchantee.scss_ et l_e-chic-a-la-francaise.scss_ juste après tes import dans _main.scss_, à la ligne 10.

Et tu verras, ton site reste aussi beau. ;) 

### Conclusion

Relis, apprend ce que qu'est le css specificity (qu'on peut aussi appeler le css score).

Conserve ton système de module. D'habitude, mon main.scss ne contient que les import, aucun style.
